### ISSUE TITLE
Boolean `false` converted to string "false"

### ISSUE THREAD

**Issue by jorgebucaran** [choojs/hyperx#42]
This makes it difficult (or impossible?) for a virtual DOM engine to determine whether the user meant `false` or "false".

```jsx
html`${true}` // yields true
html`${false}` // yields "false"
```

<img width="814" alt="screen shot 2017-02-17 at 1 02 04" src="https://cloud.githubusercontent.com/assets/56996/23029161/f1119a6a-f4ac-11e6-9c9e-40fe3157ae31.png">

If this is indeed determined to be a bug, I'd be delighted to help with if you'd be so kind to offer some help by pointing out where should I start looking in the code.

Cheers! 👋

**Comment by slaskis** [comment]
There's a PR to fix this: https://github.com/substack/hyperx/pull/35

**Comment by jbucaran** [comment]
@slaskis Why hasn't it been merged? 🤔

**Comment by slaskis** [comment]
In part because of [this](https://github.com/substack/hyperx/pull/35/files#diff-9f481e85d9e59d1d4e65e9ff18e8a7d1R26) which might make it a possible breaking change for some. So I just wanted it reviewed/accepted by someone first. 

But then I don't use this library much anymore so I kind of forgot 🤷‍♂️

**Comment by jbucaran** [comment]
Thanks. I think we can all agree hyperx should be agnostic about vdom implementations. So, perhaps your PR could be merged and that str.replace issue taken upstream to virtual-dom?

**Comment by jbucaran** [comment]
@substack Do you think #35 can be merged?
